MODTAG-101: Update to Java 17 (Update the module to Spring boot v3.0.1)
folio-org/mod-tags pull request #80
Opened 2023-01-19 11:33 UTC by MurodjonMukhamadaliev

## Purpose
https://issues.folio.org/browse/MODTAG-101#:~:text=mod%2Dtags-,MODTAG%2D101,-Update%20to%20Java: mod-tags: Update to Java 17

https://issues.folio.org/browse/MODTAG-102#:~:text=mod%2Dtags-,MODTAG%2D102,-Update%20the%20module: mod-tags: Update the module to Spring boot v3.0.0 and identify issues.

## Approach

Migrating to Spring Boot v3.0.0: https://wiki.folio.org/display/~Taras_Spashchenko/Migration+to+Spring+Boot+v3.0.0+How+to?src=contextnavpagetreemode

### Changes checklist
- [ ] API paths, methods, request or response bodies changed, added, or removed
- [ ] Database schema changes
- [ ] Interface versions changes
- [ ] Interface dependencies added, or removed
- [ ] Permissions changed, added, or removed
- [ ] Check logging.

### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

### Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2023-01-19 11:50 UTC, tatsiana-tarhonskaya commented on pom.xml
> +<!--    <log4j2.version>2.17.2</log4j2.version>-->
please remove commented line

2023-01-19 11:52 UTC, tatsiana-tarhonskaya commented on src/main/resources/application.yaml
> +    database-platform: org.hibernate.dialect.PostgreSQLDialect
it can be removed

2023-01-19 11:57 UTC, tatsiana-tarhonskaya commented on src/main/resources/application.yaml
> +          continue-on-error: true
I think we agreed to rely on spring migrator in order not to change configs. Anyway, this does not look correct(double "spring" )

2023-01-20 10:54 UTC, KyryloShulzhenko approved these changes

2023-01-20 13:45 UTC, psmagin commented on src/main/resources/application.yaml
> +        dialect: org.hibernate.dialect.PostgreSQLDialect
Please remove database-platform and dialect as this is autodetected in this new version of Spring.

2023-01-27 08:30 UTC, psmagin requested changes

2023-01-27 08:30 UTC, psmagin commented on src/main/java/org/folio/tags/ModTagsApplication.java
> +@EnableFeignClients
Why is it needed? There is no clients in the module.

2023-01-27 08:30 UTC, psmagin commented on src/main/resources/application.yaml
> +        enabled: true
There is no feign clients

2023-01-31 07:05 UTC, psmagin commented on src/main/resources/application.yaml
> +        enabled: true
Then you should have this property with false value in the module config. If it will not help, then changes in folio-spring-base is needed.

2023-02-02 12:42 UTC, merged